---

- name: Checking for Management Server Port
  register: ms_ext_mgmt_port_status
  ignore_errors: true
  wait_for:
    port: '{{ ms_ext_mgmt_port }}'
    host: '{{ local_address }}'
    timeout: 1

- name: Management Server Port Status report
  debug:
    var: ms_ext_mgmt_port_status

- name: Management server is not running
  fail:
    msg: "Management server is not running"
  when: ms_ext_mgmt_port_status | failed

- include: 4160100-main.yml
  when: opdk_version | version_compare('4.16.01', '>=')
