---
- name: Checking for Management Server Port
  register: ms_ext_mgmt_port_status
  ignore_errors: true
  wait_for:
    port: '{{ ms_ext_mgmt_port }}'
    host: '{{ private_address }}'
    timeout: 1

- name: Management Server Port Status report
  debug:
    var: ms_ext_mgmt_port_status

- name: Management server is not running
  fail:
    msg: "Management server is not running"
  when: ms_ext_mgmt_port_status | failed

- name: Construct name of edge response validate file
  cache:
    key: 'onboarding_config_file_path'
    value: '{{ opdk_installer_path }}/edge-response-validate-{{ opdk_version }}-{{ region }}.conf'

- name: Remove old apigee-provision file
  file:
    path: '{{ onboarding_config_file_path }}'
    state: absent
  when: provided_onboarding_config_file_path is not defined

- name: Prepare onboarding config file
  template:
    src: '{{ onboarding_config }}.j2'
    dest: '{{ onboarding_config_file_path }}'
    mode: 0644
  when: provided_onboarding_config_file_path is not defined

- name: Copy provided onboarding config file
  copy:
    src: '{{ provided_onboarding_config_file_path }}'
    dest: '{{ onboarding_config_file_path }}'
    mode: 0644
  when: provided_onboarding_config_file_path is defined
